default: &default
  adapter: postgresql
  encoding: unicode
  username: samira
  password: samira123
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: web_girls_development

test:
  <<: *default
  database: web_girls_production

production:
  <<: *default
  database: web_girls_test


